feat: 시군구 목록 API
wanted-quantum-jump/FoodieFinder pull request #34
Opened 2023-11-03 02:08 UTC by seoyoon047

## 🚀 풀 리퀘스트 요약
- 시군구 데이터를 목록으로 반환하는 API를 구현한다
- 기존 만들어진 SggRepository에서 데이터를 받아왔습니다

## 📋 변경 사항

- [x] 새로운 기능 추가

## 📌 체크리스트

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 모든 테스트를 통과합니다.

## 📎 관련 이슈

#19 

## 🙌 리뷰 및 피드백

2023-11-03 04:57 UTC, O0oO0Oo approved these changes
크게 문제없어 보입니다. 👍

2023-11-03 04:57 UTC, O0oO0Oo commented on src/main/java/com/foodiefinder/common/dto/ResponseDto.java
> +@JsonInclude(JsonInclude.Include.NON_NULL)
이건 처음 봤네요. 하나 배워갑니다. 👍

2023-11-03 08:03 UTC, hyerijang requested changes

2023-11-03 08:03 UTC, hyerijang commented on src/main/java/com/foodiefinder/cities/controller/CityController.java
> +@RequestMapping("/cities")
```suggestion
@RequestMapping("/api/cities")
```

팀 컨벤션에 따르면 api 경로는 /api로 시작해야합니다🥺

2023-11-03 08:03 UTC, hyerijang commented on src/main/java/com/foodiefinder/cities/controller/CityController.java
> +        return this.sggService.getCities();
지금 해당 api를 실행하면
```
[
    {
        "status": 200,
        "data": {
            "id": 1,
            "dosi": "강원",
            "sgg": "강릉시",
            "lon": 128.8784972,
            "lat": 37.74913611
        }
    },
    {
        "status": 200,
        "data": {
            "id": 2,
            "dosi": "강원",
            "sgg": "고성군",
            "lon": 128.4701639,
            "lat": 38.37796111
        }
    },

//...생략
]
```
이렇게 각 **데이터 마다 200 코드**가 포함되는데 **보통 목록 자체에는 상태코드 1개만 포함**된다고 알고 있어서요. 뭔가 서비스 쪽에서 맵핑할 때 잘못하신것 같습니다. 😅

2023-11-03 08:03 UTC, hyerijang commented on src/main/java/com/foodiefinder/cities/service/CityService.java
> +                .orElse(Collections.emptyList());
Optional에서 null이 발생하면 커스텀 예외로 예외처리를 하고 결과 상태코드도 **500번대** (501 구현되지 않음?) 로 주셔야 할 것 같습니다. 지금 로직대로면 비어있어도  200이 올 것 같네요. 🤔

2023-11-03 08:14 UTC, hyerijang commented on src/main/java/com/foodiefinder/cities/controller/CityController.java
> +        return this.sggService.getCities();
그리고 지금보니 응답이 [ 로 시작하는데... response 의 배열/리스트을 리턴하신 거 같네요. JSON 데이터는 일반적으로 중괄호 {}로 시작하고 끝나야 하고, response 의 data 안에 배열을 넣어주셔야합니다.

2023-11-03 08:28 UTC, hyerijang requested changes

2023-11-03 08:28 UTC, hyerijang commented on src/main/java/com/foodiefinder/cities/service/CityService.java
> +                .collect(Collectors.toList());
지금 Sgg를 그대로 ResponseDto의 Data에 넣어주시고 있는데, 이러면 결과적으로 유저에게 Sgg 객체가 그대로 노출됩니다. 유저에게 보여주면 안되는 필드까지 보여주게 되구요. (만약 User객체를 이렇게 넣었다면 비밀번호까지 다 보였을 것)

**객체를 그대로 노출시키는 건 굉장히 위험**합니다. 이 테이블은 연관관계가 없지만, 만약 연관관계가 있었다면 Json 파싱 과정에서 `무한 참조`가 발생하게 됩니다.


- 무한참조
![image](https://github.com/wanted-quantum-jump/FoodieFinder/assets/46921979/fcff569d-47ac-4b3a-9169-e2da2db1fb43)

2023-11-03 08:38 UTC, hyerijang commented
ResponseDto를 하나만 만들어서 재사용하려다 보니 앞서 언급한  문제들이 발생하는 것 같습니다. 각 서비스 메소드 별로 ResponseDto를 따로 만드시는 게 꼭 필요한 정보만 노출할 수 있고, 엔티티에 의존하지 않아 더 좋을 것 같습니다.

2023-11-04 14:35 UTC, merged

2023-11-04 17:18 UTC, hyerijang commented
앗 머지가 끝나고 리뷰 요청 하신걸 봤네요. 정상 동작하는 것 확인 했습니다! 

수정 요청이 많았는데 😅 적극적으로 받아들여주셔서 감사합니다. 오늘 하루 고생하셨어요! 

한가지 아쉬운 점이라면, 현재 "data" { } (중괄호)  안에  citesResponses [ ] 배열이 들어가 있는데,  REST API에서는 보통  data : [ ] (대괄호) (data가 배열임) 이렇게 표현합니다. 음.. 제가 이 부분은 어제 코멘트를 좀 헷갈리게 썼던거 같네요. 죄송합니다. 🤐


### 현재 API를 실행시 응답

``` json
{
    "status": 200,
    "message": "Success",
    "data": {
        "citesResponses": [ //data 안에 citesResponses 배열
            {
                "dosi": "강원",
                "sgg": "강릉시",
                "lon": 128.8784972,
                "lat": 37.74913611
            },
... 생략 ... 

     ]
}
```

아래는 올바른 예시로 참고하시기 좋을 것 같아 가져왔습니다. 
[REST API Examples - Example 5: Load multiple rows into a table](https://help.hcltechsw.com/onedb/1.0.1/rest/rest_011.html#rest_011__load_docs:~:text=1%2C%0A%20%20%20%20%22responseTime%22%3A%2035%0A%7D-,Example%205%3A%20Load%20multiple%20rows%20into%20a%20table,-To%20load%20(insert))